### ISSUE TITLE
No 4 digit code when playing a locally hosted version

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/liberty-bikes#180]
Another item we have noticed when demoing the game at conferences, is that having to type in the 4 digit round code is cumbersome.  Its particularly hard to do when your trying to engage with the attendees and hurry to get them into a round of the game.  

Secondly, once you play around, the UI on the mobile device bumps you back out where you have to re-enter the code after each game played.  Would be nice to have it where you didnt bump the user out of the game, but auto queued them for the next round since we typically just hand the device to the next person that walks up at the conference.

This is somewhat tied to #171 as well for ease of usage.

**Comment by aguibert** [comment]
we have a "single party" mode for locally hosted settings, does that solve this request?

From the readme:
```
./gradlew start frontend:open -DsingleParty=true
```

**Comment by hlhoots** [comment]
Ahh...I bet it does.  Totally missed that option in the docs!  Thanks @aguibert
