### ISSUE TITLE
Dashboard showing Health, Metrics and Open Tracing

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/liberty-bikes#186]
Create a dashboard showing Health, Metrics and Open Tracing.

Sebastian Dashner has created a Grafana dashboard for Liberty and has a demo of running Prometheus/Grafana in Docker which might be a good starting point.

**Comment by aguibert** [comment]
This blog post may be of use for figuring out how to connect Liberty with a dashboard:
https://blog.sebastian-daschner.com/entries/openliberty-monitoring-prometheus-grafana
