### ISSUE TITLE
dockerStart fails after clean due to missing Postgres jar

### ISSUE THREAD

**Issue by realModusOperandi** [OpenLiberty/liberty-bikes#234]
Performing the docker-compose start command (`dockerStart and/or `composeUp`) after `clean` (but before running the standard start command) causes the compose up step to fail building the player-service image:

```
Step 3/6 : ADD --chown=1001:0 build/libs/postgresql-*.jar /config/postgresql
ADD failed: no source files were specified
```

**Comment by aguibert** [comment]
Fixed by #237 and also added a TravisCI pipeline in #238 so issues like this don't happen in the future
